// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvnpLe0y7wKLeTAqv2f1UX6zZGCiUEKr0',
    appId: '1:219290566799:web:9f87e54c83c7b9924630fa',
    messagingSenderId: '219290566799',
    projectId: 'wardrobe-ai-31325',
    authDomain: 'wardrobe-ai-31325.firebaseapp.com',
    storageBucket: 'wardrobe-ai-31325.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdnNqwQ9gENIk_EeaVZ3H6Mw8_XdbqqYM',
    appId: '1:219290566799:android:9fe58020264bc3134630fa',
    messagingSenderId: '219290566799',
    projectId: 'wardrobe-ai-31325',
    storageBucket: 'wardrobe-ai-31325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1otBCTxHGddvDgBLvFC79qF3p02DU-M4',
    appId: '1:219290566799:ios:e05068f117ef630a4630fa',
    messagingSenderId: '219290566799',
    projectId: 'wardrobe-ai-31325',
    storageBucket: 'wardrobe-ai-31325.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1otBCTxHGddvDgBLvFC79qF3p02DU-M4',
    appId: '1:219290566799:ios:e05068f117ef630a4630fa',
    messagingSenderId: '219290566799',
    projectId: 'wardrobe-ai-31325',
    storageBucket: 'wardrobe-ai-31325.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvnpLe0y7wKLeTAqv2f1UX6zZGCiUEKr0',
    appId: '1:219290566799:web:df20ae707afd19394630fa',
    messagingSenderId: '219290566799',
    projectId: 'wardrobe-ai-31325',
    authDomain: 'wardrobe-ai-31325.firebaseapp.com',
    storageBucket: 'wardrobe-ai-31325.firebasestorage.app',
  );
}
